{{- if .Values.configMap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name | default (include "app-kubiaki.fullname" .) }}
  labels:
    {{- include "app-kubiaki.labels" . | nindent 4 }}
{{- with .Values }}
data:
  {{- toYaml .| nindent 2}}
{{- end }}
{{- end -}}